apiVersion: metalmatze.de/v1alpha1
kind: CockroachDB
metadata:
  name: groovelink
  namespace: groovelink-dev
  labels:
    app.kubernetes.io/component: database
spec:
  replicas: 3
  image: cockroachdb/cockroach:v20.1.0
  resources:
    requests:
      cpu: '500m'
      memory: 1Gi
    limits:
      cpu: '2'
      memory: 4Gi
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: cockroachdb-groovelink
  namespace: groovelink-dev
spec:
  scaleTargetRef:
    apiVersion: metalmatze.de/v1alpha1
    kind: CockroachDB
    name: groovelink
  minReplicas: 3
  maxReplicas: 9
  metrics:
    - type: Pods
      pods:
        metric:
          name: cockroachdb_sql_select_count
          selector:
            matchLabels:
              service: cockroachdb-groovelink
        target:
          type: Value
          averageValue: 15
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: groovelink-frontend
  namespace: groovelink-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: groovelink-frontend
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Pods
      pods:
        metric:
          name: groovelink_http_requests
          selector:
            matchLabels:
              service: groovelink-frontend
        target:
          type: AverageValue
          averageValue: 10
